apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airrfed-stage-cluster-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgAvOZVcEloTcgNI9+6vu4LjkTHlIRL7IeIWV/i/uSupjkYEHmPDA4tN4kJCC9kWZaHsfgp0UoSkEvTNCONG0TzUsgcfr/nAXkqYzQmOBA6YFwaVCsOarhB/yYeeNmGYdu/NzrVMu3qBAGP4WI5J8xMY6BGP8mgAwVzphDzOQmfKtCnKf941OyXak/+fHF88s6BMwmJlEQn7JWrLYOiYSqlyudcoirHo2AHCJ/Rgg9DURHaK2t0w3yL1eqcNp149nUK479KnDByXTWDFqbyEAcvXyKQnsW5mWyAmPoUlvQoz+x72Bb0ut0erthibg1i5WlCYoI8AvaBC4d7fzJ+IT7xAuWVkcV9zVtBVflJwzhFCzfq9oIvRVDEd9iNmQLNxeGfJmRuimG3M6sbQ9dKREG8xMYKG1MnItNGJAdmIW1P049v9PfipzP7OMz2I5AGNFsyRlPMH16TheEmyBn3CdI5mONhhfi8mD4IQUbxt/s2GOhWaAHzyHQ4R6V/ZcXhMeLXSEAZxHKJzhJWImwC5VOI+T2tglXUwV9z+0SI+1MGcwZuAvBBNnRcdVja9PZWxkqtiUN105zUgEpaYVA2uXT6S6O0SEolMM+x83HIply9bv8uQdfyMXnpuBsvdG6LcBIPSPcrEB8ld1PAxYsl7USCtyfP17VEXLMyLg66doJOnFVh1b7NH+mhSlQ1mIgmTkflLV45ChNoyDA54MDc3YEgyWBiyi/dvWyfL3u78RIZqFimTcHbJtqDib4PERmP62wMNwZGoE17xomO50O6HpuIG/+pIOaatUx77PgkqLUB2HAgAmtm/aie1o42RybgXNJlIXkj4hJwT6/4BGKbxuSTmx6NCKYwTMEmC+P5LU7NomLQCR9X3ufGH6t2V8ougVcdYR13JX4gMgmc40cQIYO4RrBkTAimVhNojIbetCVQnyLZHG7CA7tDxX9uxNhUp2rBnZJUjoBZJj2VyCtDpM6SxqoJSATE6uFtw34JnDOcbaZd+vvFHTpyub91iDFQedUb3Ck8zxefyV4Ygjb2z08MTg/qKnRMtutDzbVLo0Qi/VOJ36kEm3afX6KJ/jVsRgWfgDgeQNddMSmMbsA/OmX6MUVUBf/lS+sI3ZF608VDTAwzlGw/QXU3AsFine8POdyuEW5XScCduNf/r89ZcpUyXEmv2E9Kvn/Ch8e7OerJKBALZjxLyDsRuuAaPy5Zaqai0YputgPb1m72c7SS1N8Ihp84QFs001pA0QwHlYSthRIn7YcMZZlgrMb+B5iJ0jomGCuAS2GDIUgUg3c4ttme4Le/KAjfpw+SpyTH8W/DZeQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: airrfed-stage-cluster-credentials
      namespace: capi-self

