---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bo307-test-cluster-config
  namespace: capi-self
data:
  values.yaml: |
    # Must match the name of the (sealed) secret in credentials.yaml
    cloudCredentialsSecretName: bo307-test-cluster-credentials

    kubernetesVersion: 1.30.1
    machineImageId: 6f8e1b6f-3e5e-45fe-adb2-f35ba2909396

    clusterNetworking:
      externalNetworkId: 57add367-d205-4030-a929-d75617a7c63e
      internalNetwork:
        networkFilter:
          name: portal-internal

    controlPlane:
      machineFlavor: vm.ska.cpu.general.small
      machineCount: 3

    nodeGroups:
      - name: workers
        machineFlavor: vm.ska.cpu.himem.eighth
        autoscale: true
        machineCountMin: 2
        machineCountMax: 9

    # Configuration for the cluster autoscaler
    autoscaler:
      # The image to use for the autoscaler component
      image:
        repository: registry.k8s.io/autoscaling/cluster-autoscaler
        pullPolicy: IfNotPresent
        tag: v1.30.0
      imagePullSecrets: []
      # Any extra args for the autoscaler
      extraArgs:
        # Make sure logs go to stderr
        logtostderr: true
        stderrthreshold: info
        # Output at a decent log level
        v: 4
        # Cordon nodes before terminating them so new pods are not scheduled there
        cordon-node-before-terminating: "true"
        # When scaling up, choose the node group that will result in the least idle CPU after
        expander: least-waste,random
        # Allow pods in kube-system to prevent a node from being deleted
        skip-nodes-with-system-pods: "true"
        # Allow pods with emptyDirs to be evicted
        skip-nodes-with-local-storage: "false"
        # Allow pods with custom controllers to be evicted
        skip-nodes-with-custom-controller-pods: "false"

    addons:
      # Use the cilium CNI
      cni:
        type: cilium

      # Enable the monitoring stack
      monitoring:
        enabled: true

      # Disable NFD and the NVIDIA/Mellanox operators
      nodeFeatureDiscovery:
        enabled: false
      nvidiaGPUOperator:
        enabled: false
      mellanoxNetworkOperator:
        enabled: false

      # ingress:
      #   enabled: true
      #   nginx:
      #     release:
      #       values:
      #         controller:
      #           service:
      #             loadBalancerIP: "128.232.226.88"
      #           allowSnippetAnnotations: true
                









