apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bo307-test-cluster-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgAaFOZ7zV4LXsueJVmI7ibwAK79ERSLv+Ged0DIEVzgaY605Ua4efZCQiXg72TNfXFrRU5TXJS6CKWcos2TMEhtL+uL8XE6nqcvftOHp9E/IK4xlTmQ11oRztooq0pVPpiR/vcbJ2JWarOgXmE6FcwOIHKlAJt3szl0BAVCCucpDwpaZx2/fsrlxc5VHxh6iILWfh25bGCMABrFxgPH6c2gyObSmS2MOUiuvX6vudKLhayC6KRfH7snn5IEU/TXqIdzshH4/lhbASHnFPWxqebtvCX0jz3EPK7epVU1ZdcUjFzPl40Atpv7iJuXGzMXOmIPjBVP57vwXQs9vzYQQ+1pHO6DvnH8pmJtuIVLHNfoKnPlBErmCU7bmeMyAP4W/D5KOtrXLPLvSqa+sA5Wcy3KhYN+QdG3twKfrSI9J9Nb4ANN4lvWBKfowkt1VDshGBsuViF86sqbSLvF9HejuQnJW3/p6XNp1xMRkLwt18gm5joYOVvya0HuJ/JDKRYMMnd9PTKZR6hJzepYQ4RtgYk3pv3vaPwCV0HpPcBtGu1kNqRjaAye3EGDOl5+Ien+9KnVSsC90MpVMObNXi6/pya4gQgvBdbPpfwiIRTaMnBnsynqNn9N0saMO2/C5sC9e+ZUNAgIKxW86elisgnZya8o+4einXjbqpknQJ7oRQTOJ5i8owpXpH01zC02PQMeACG3NS+LEZHkjQSKgGqnQvkmGwi3k7wuR5gb7TjDOfuhPOzB6db+cozKY1Th0EFm5gSGLeaI2R0WETPOv0Dw8U8VqhUMjP/AFuRFMYm8dagagrnyULj4BqgquNQU7EgZMLVebJdY/kB++6tJorp1ibrqgKj2LZ7XtqTbYO8LO0OutF0wCIExwSzlxe8vvdYTMLsfZS4rNAB1WaKHKdtvgB/Q+t2CNvvd7lyAyEVKTFMkWFO5UrUOY02uT/UwadNT6qNKKIZshSffMuEOu4ecDTnpUMELa1apOT7rL0qjTDoqpNptv44LAD5TUOaEBZwpjCff0OSDtNdI3XPAnqIHszzTrf5EKlDV6v7qZoHFMfDgOa+0iH5vDOFBPVKw8X9DvDLI8XH1AJo3cYnVWIqCnnLYRc7BjuOAizvVGh4jhu8ubbjWPoIXVnM92EwtP9EKdQK9rGd6J7XnJBFGpzBfE6Nb5UORDZ7JgUnTh29ivp700V8o2DnifCUFNOvFzDgnMy6dXKd6ZhiZvV/I81OVCZrC6JWBXRoL5MCFWhvOjE3PUSFnzLN9M+D+0GHh+VSSQBlzPRY3FQyOZG+ZIUfuGopB43B6Cw91iAb2g+8SsB2cSg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: bo307-test-cluster-credentials
      namespace: capi-self

